config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
  get :dashboard, to: "categories#index"

  resources :profile, only: [:show, :new, :update]
  resources :articles, only: [:index, :new, :show, :create, :update, :destroy]
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :votes, only: [:create, :destroy]
  resources :articles do
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :followings, only: [:index, :create, :destroy]
  resources :events, only: [:index, :show, :new, :create, :destroy]
  resources :invitations, only: %i[create update destroy]
  resources :guestlists, only: [:index]
  resources :hostings, only: [:index]
  resources :participations, only: [:index]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  belongs_to :category, class_name: 'Category', foreign_key: :category_id

  has_one_attached :image
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  scope :most_recent_by_category, lambda {
    from(
      <<~SQL
        (
          SELECT articles.*
          FROM articles JOIN (
            SELECT category_id, max(created_at) AS created_at
            FROM articles
            GROUP BY category_id
          ) latest_by_category
          ON articles.created_at = latest_by_category.created_at
          AND articles.category_id = latest_by_category.category_id
        ) articles
      SQL
    )
  }

  def self.ransackable_attributes(_auth_object = nil)
    %w[id title body created_at category_id user_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update destroy]

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    article = Article.new(article_params.merge(creator: current_user))

    return unless article.save

    redirect_to root_path, notice: 'Article was successfully created.'
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy
    redirect_to categories_path, notice: 'Article was destroyed.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :image, :user_id, :category_id)
  end
end

app/views/articles/_article_form.html.erb
<div class="border border-dark py-3 px-5">
  <%= form_with model: @article do |f| %>
    <div class="mb-3">
      <b><%= f.label "Article Title", class: "form-label" %></b><br />
      <%= f.text_field :title, class: "form-control form-control-sm" %>
    </div>
    <div class="mb-3">
      <b><%= f.label "Article Body", class: "form-label" %></b><br />
      <%= f.text_area :body, size: "100x4", class: "form-control form-control-sm" %>
    </div>
    <div class="d-flex flex-row mb-3">
      <b class="pe-4"><%= f.label "Article Topic", class: "form-label" %></b><br />
      <%= f.collection_select :category_id, Category.order(:id), :id, :topic, class: "form-control" %>
    </div>
    <div class="d-flex flex-row mb-3">
      <b class="pe-4"><%= f.label :image, class: "form-label" %></b>
      <%= f.file_field :image, class: "form-control form-control-sm" %>
    </div>
    <div class="d-flex flex-row justify-content-end mb-3">
      <%= f.submit "Submit Article", class: "btn btn-outline-primary py-0" %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="d-flex flex-row justify-content-center mt-5">
  <div class="w-75">
    <h4 class="mb-4"><b>Edit Article</b></h4>
    <%= render 'article_form', locals: { article: @article, categories: @categories } %>
    <p class="mt-3"><%= link_to 'Back', categories_path %></p>
  </div>
</div>

app/views/articles/index.html.erb
<div>
  <div class="my-5 mx-5">

  <%= render 'search/form' %>

  <table class="table">

    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"><%= sort_link(@q, :title, "Title", default_order: :asc) %></th>
        <th scope="col"><%= sort_link(@q, :body, "Article Content", default_order: :desc ) %></th>
        <th scope="col"><%= sort_link(@q, :creator, "Creator") %></th>
        <th scope="col"><%= sort_link(@q, :created_at, "Created at", default_order: :asc) %></th>
        <th scope="col">Link to Article</th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article|%>
        <tr>
          <td><%= image_tag( article.image, height: 50, width: 50, class: "" ) if article.image.attached? %></td>
          <td><small class="pt-0"><%= truncate article.title, length: 40 %></small></td>
          <td><small ><%= truncate article.body, length: 40 %><small></td>
          <td><%= image_tag( article.creator.avatar, height: 30, width: 30, class: "rounded-circle me-2" ) if article.creator.avatar.attached? %><small><%= article.creator.username %></small></td>
          <td><small><%= article.created_at.strftime("%b %d %Y") %></small></td>
          <td><small class="pt-2"><%= link_to 'Go to', article_path(article) %></small></td>
        </tr>
      <% end %>
    </tbody>

  </table>
 
</div>

app/views/articles/new.html.erb
<div class="d-flex flex-row justify-content-center mt-5">
  <div class="w-75">
    <h4 class="mb-4"><b>New Article</b></h4>
    <%= render 'article_form', locals: { article: @article, categories: @categories } %>
    <p class="mt-3"><small><%= link_to 'Back', categories_path %></small></p>
  </div>
</div>

app/views/articles/show.html.erb
<div class="border border-dark rounded my-5 mx-5">
  <div class="my-3 mx-5">
  
    <div class="d-flex flex-row justify-content-start">
      <%= image_tag( @article.image, height: 120, width: 120, class: "me-5" ) %> 
      <div class="mt-3">
        <strong class="me-4"><%= @article.title %></strong>
        <small><%= @article.category.topic%></small>
        <div class="d-flex flex-row justify-content-start mt-3">
          <p class="me-3"><small><strong>By: </strong></small></p>
          <%= image_tag( @article.creator.avatar, height: 30, width: 30, class: "rounded-circle" ) if @article.creator.avatar.attached? %>
          <p class="ms-2"><small><%= @article.creator.username %></small><p>
          <% if current_user %>
            <p class="ms-5"><small><%= link_to 'View Profile', profile_path(@article.creator), class: "" %></small></p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="mt-5">
      <%= @article.body %>
    </div>

    <div class="d-flex flex-row mt-3">
      <div class="mt-1 me-5">
        <span><small><strong>Votes: </strong><%= @article.votes.count %></small></span>
      </div>
      <% if current_user %>
        <% vote = current_user.votes.find_by(article: @article) %>
        <% if vote.nil? %>
          <%= button_to votes_path, params: { vote: {:article_id => @article.id } }, method: :post, class: "" do %>
            <%= image_tag "heart.jpg", height: "15", class: "" %>
          <% end %>
        <% else %>
          <%= button_to vote_path(vote), method: :delete, class: "-5" do %>
            <%= image_tag "heart-full.jpg", height: "15", class: "" %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <% if current_user %>
      <div>
        <%= render '/comments/show' %>
      </div>
      <div>
        <%= render '/comments/comment_form', article: @article, parent: nil %>
      </div>
      <% if  @article.creator == current_user || current_user.admin? %>
        <div class="d-flex flex-row justify-content-end mt-2">
          <p class="mt-2 me-3"><small>Manage Article:</p></small>
          <div class="mt-1 me-3">
            <%= link_to edit_article_path(@article), class: "" do %>
              <%= image_tag "Edit.jpg", width: "25", class: "" %>
            <% end %>
          </div>
          <div>
            <%= button_to article_path(@article), method: :delete, class:"" do%>
              <%= image_tag "Trash-can.jpg", width: "15", class: "trash" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="mt-3">
      <small><%= link_to 'Back', categories_path %></small>
    </div>

  </div>
</div>