config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
  get :dashboard, to: "categories#index"

  resources :profile, only: [:show, :new, :update]
  resources :articles, only: [:index, :new, :show, :create, :update, :destroy]
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :votes, only: [:create, :destroy]
  resources :articles do
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :followings, only: [:index, :create, :destroy]
  resources :events, only: [:index, :show, :new, :create, :destroy]
  resources :invitations, only: %i[create update destroy]
  resources :guestlists, only: [:index]
  resources :hostings, only: [:index]
  resources :participations, only: [:index]
end

app/views/shared/_eventnav.html.erb
<div class="dropdown">
  <button class="btn btn-outline-dark dropdown-toggle txt-e" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Navigate Events
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <div>
      <small><%= link_to('Create an Event', new_event_path, class: "link lnk-h ms-1") %></small>
    </div>
    <div>
      <small><%= link_to('My Hosted Events', hostings_path, class: "link lnk-h ms-1") %></small>
    </div>
    <div>
      <small><%= link_to('My Events Participation', participations_path, class: "link lnk-h ms-1") %></small>
    </div>
    <div>
      <small><%= link_to('All Events', events_path, class: "link lnk-h ms-1") %></small>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-row justify-content-around align-items-center text-bg-dark">
 
    <div>
      <small><h5 class="txt-fh mt-0 mx-3"> Sophia </small><span class=""></h5>
    </div>
  
  <div> 
    <div class="d-flex flex-row mt-2">
      <p class="txt-f px-2">Privacy Policy</p>

      <p class="txt-f px-4">Terms & Conditions</p>
      
      <p class="txt-f pe-1"> &copy; Copyright 2021</p>

      <p class="txt-f">All rights reserved</p>
    </div>
  </div>

    <p class="txt-f mt-2">Developed by
      <a href='https://github.com/German-Cobian/Sophia' target=''>German Cobian</a>
    </p>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-row justify-content-around align-items-center border-bottom pt-2 text-bg-dark">

  <div class="mb-2 mx-3">
    <h5 class="txt-n2"> Sophia <span class=""></h5>
  </div>

  <div class="d-flex flex-row justify-content-between mb-2">
    <div class="dropdown">
      <button class="btn btn-outline-secondary dropdown-toggle txt-n" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Navigate Sophia
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <div class="me-5">
          <small><%= link_to("Home", root_path, class: "link lnk-h ms-3") %></small>
        </div>
        <% Category.find_each do |category| %>
          <%= link_to category.topic, category, class: "dropdown-item txt-drop me-4" %>
        <% end %>
        <div class="me-5">
          <small><%= link_to("Search", articles_path, class: "link lnk-h ms-3") %></small>
          <small><%= link_to("Events", events_path, class: "link lnk-h ms-3") %></small>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex flex-row mb-2">

    <% if current_user %>

      <div class="ms-3 me-5 mt-2">        
       <h5 class="txt-n"><%= current_user.username %></h5>
      </div> 

      <div class="pe-3">
        <%= link_to "Create Article", new_article_path, class:"txt-n" %>
      </div>

      <% if current_user.admin? %>
        <div class="pe-3">  
          <%= link_to "Manage Categories", new_category_path, class:"txt-n" %>
        </div>
      <% end %>

      <div class="pe-3">
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete}, class: "txt-n" %>
      </div>

    <% else%> 

      <div class="px-2">
        <%= link_to "Sign In", new_user_session_path, class: "txt-n" %>
      </div>

      <div class="px-2">
        <%= link_to 'Sign Up', new_user_registration_path, class: "txt-n" %>
      </div>

    <%end%>
  </div>    
  
</div>