config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
  get :dashboard, to: "categories#index"

  resources :profile, only: [:show, :new, :update]
  resources :articles, only: [:index, :new, :show, :create, :update, :destroy]
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :votes, only: [:create, :destroy]
  resources :articles do
    resources :comments, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :followings, only: [:index, :create, :destroy]
  resources :events, only: [:index, :show, :new, :create, :destroy]
  resources :invitations, only: %i[create update destroy]
  resources :guestlists, only: [:index]
  resources :hostings, only: [:index]
  resources :participations, only: [:index]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy

  has_one :most_recent_article, lambda {
                                  merge(Article.most_recent_by_category)
                                }, class_name: 'Article', inverse_of: :category

  validates :topic, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  def index
    Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def category_params
    params.require(:category).permit(:topic)
  end
end

app/views/categories/_category_form.html.erb
<div class="border border-dark py-3 px-5">
  <%= form_with model: Category.new, url: categories_path, method: :post, local: true do |f| %>
    <div class="mb-3">
      <b><%= f.label "Topic Category", class: "form-label" %></b><br />
      <%= f.text_field :topic, class: "form-control form-control-sm" %>
    </div>
    <div class="d-flex flex-row justify-content-end mb-3">
      <%= f.submit "Submit Category", class: "btn btn-outline-primary py-0" %>
    </div>
  <% end %>

  <% categories = Category.all%>
  <% categories.each do |category|%>
    <div class="d-flex flex-column mb-3">
      <div class="d-flex flex-row justify-content-between">
        <%= category.topic %>
        <%= button_to category_path(category), method: :delete, class: "py-0 me-5" do %>
          <%= image_tag "Trash-can.jpg", width: "15", class: "" %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/categories/index.html.erb
<div class="my-5">

  <h4 class="ms-5"><b>Most Popular</b></h4>
  <div class="cat1-container d-flex flex-row justify-content-center mt-3 mx-5 border border-dark rounded">
    <% popular = Vote.popular %>
    <% popular.each do |vote| %>
      <div class="d-flex flex-column flex-md-row justify-content-around w-100" >
        <div class="img-pop mt-3">
          <% if vote.article.image.attached? %> 
            <%= image_tag( vote.article.image, height: 270, width: 270, class: "me-5" ) %>
          <% else %>
            <%=  image_tag("Default_img.jpg", height: 270, width: 270, class: "me-5" ) %>
          <% end %>
        </div>
        <div class="mt-3 mx-5">
          <h5><%= vote.article.title %></h5>
          <div class="d-flex flex-row ms-2">
            <%= image_tag( vote.article.creator.avatar, height: 30, width: 30, class: "rounded-circle" ) %></span>
            <p class="ms-2"><small><%= vote.article.creator.username%></small></p>
          </div>
          <p class="mt-3"><small><%= truncate vote.article.body, length: 200 %></small></p>
          <p><small><%= link_to 'Read more', article_path(vote.article), class: "" %></small></p>
        </div>
      </div>
    <% end %>
  </div>

  <h4 class="mt-4 ms-5"><b>Most Recent</b></h4>
  <div class="d-flex flex-wrap justify-content-between mx-5" >
    <% categories = Category.includes(:most_recent_article) %>
    <% categories.each do |category| %>
      <div class="cat2-container d-flex flex-column align-items-center border border-dark rounded mt-3 mx-1 ">
        <div>
          <h6 class="mt-3"><%= link_to category.topic, category %></h6>
        </div>
        <div>
          <% if category.most_recent_article&.image %> 
            <%= link_to image_tag( category.most_recent_article&.image, height: 120, width: 120, class: "me-5" ) %>
          <% else %>
            <%= image_tag("Default-img.jpg", height: 120, width: 120, class: "me-5" ) %>
          <% end %>
        </div>
        <div class="my-3 mx-2">
          <small class="cat-title"><%= truncate category.most_recent_article&.title, length: 35 %></small>
        </div>
      </div>
    <% end %>
  </div>

<div>

app/views/categories/new.html.erb
<div class="d-flex flex-row justify-content-center mt-5">
  <div class="w-75">
    <h4 class="mb-4"><b>New Category</b></h4>
    <%= render 'category_form', category: @category %>
    <p class="mt-3"><small><%= link_to 'Back', categories_path %></small></p>
  </div>
</div>

app/views/categories/show.html.erb
<div class="my-5">
  <h4 class="ms-5"><b><%= @category.topic %></b></h4>
  <div class="d-flex flex-wrap justify-content-start mx-5">
    <% @category.articles.order('created_at DESC').each do |article|%>
      <div class="cat3-container d-flex flex-column flex-lg-row border border-dark rounded mt-3 ml-2">
        <div class="img-cat">
          <%= image_tag(article.image, height: 220, width: 220, class: "me-5" ) %> 
        </div>
        <div>
          <h6 class="mt-2 mx-2"><b><%= article.title %></b></h6>
          <div class="d-flex flex-row ms-2">
                <%= image_tag( article.creator.avatar, height: 30, width: 30, class: "rounded-circle" ) if article.creator.avatar.attached? %></span>
                <p class="ms-2"><small><%= article.creator.username%></small></p>
          </div>
          <p class="mx-2"><%= truncate article.body, length: 200 %></p>
          <p class="ms-2"><small><%= link_to 'Read More', article_path(article) %></small></p> 
        </div>
      </div>
    <% end %>
  </div>
</div>